In [1]:
import pandas as pd

In [2]:
!dir

 Volume in drive C is OS
 Volume Serial Number is FCC3-CE53

 Directory of C:\Users\geitb\Kopenhagen\KopenhagenResearch\scripts_research\hebrew_spelling_variation\preprocess_data\data

09-02-2023  13:47    <DIR>          .
15-01-2023  15:03    <DIR>          ..
09-02-2023  13:47    <DIR>          .ipynb_checkpoints
09-02-2023  10:17            31.308 check_middle_syllables.ipynb
09-02-2023  09:56         5.130.794 matres_dss.csv
09-02-2023  09:56        31.154.695 matres_mt.csv
09-02-2023  10:00        31.666.189 mt_dss_with_middle_syllables.csv
               4 File(s)     67.982.986 bytes
               3 Dir(s)  594.897.592.320 bytes free

In [3]:
dat = pd.read_csv('mt_dss_with_middle_syllables.csv', sep='\t')

C:\Users\geitb\AppData\Local\Temp/ipykernel_26532/3648146535.py:1: DtypeWarning: Columns (10,11,14,25) have mixed types. Specify dtype option on import or set low_memory=False.
  dat = pd.read_csv('mt_dss_with_middle_syllables.csv', sep='\t')

In [4]:
dat.head()

,tf_id,scroll,book,chapter,verse,lex,g_cons,stem,pattern,pattern_g_cons,...,other_vowel_ending,final_h,line,column,has_pronominal_suffix,has_prefix,has_hloc,has_nme,type,vowel_letter
0,2,MT,Genesis,1,1,R>CJT/,R>CJT,R>CJT,CMCMC,CMCMC,...,NaN,noH,-,-,0,1,0,0,last,J
1,2,MT,Genesis,1,1,R>CJT/,R>CJT,R>CJT,CMCMC,CMCMC,...,NaN,noH,-,-,0,1,0,0,first,>
2,4,MT,Genesis,1,1,>LHJM/,>LHJM,>LH,CCC,CCCMC,...,NaN,noH,-,-,0,0,0,1,last,NaN
3,4,MT,Genesis,1,1,>LHJM/,>LHJM,>LH,CCC,CCCMC,...,NaN,noH,-,-,0,0,0,1,first,NaN
4,7,MT,Genesis,1,1,CMJM/,CMJM,CMJ,CCC,CCCC,...,NaN,noH,-,-,0,1,0,1,last,NaN

In [5]:
dat.type.value_counts()

last      107586
first     107586
single     73167
second       647
third          4
Name: type, dtype: int64

In [6]:
dat.query("type=='third'")

,tf_id,scroll,book,chapter,verse,lex,g_cons,stem,pattern,pattern_g_cons,...,other_vowel_ending,final_h,line,column,has_pronominal_suffix,has_prefix,has_hloc,has_nme,type,vowel_letter
53201,111708,MT,Deuteronomy,32,20,THPKWT/,THPKT,THPKT,CCCCC,CCCCC,...,NaN,noH,-,-,0,0,0,0,third,NaN
201360,1893410,1Q5,Deuteronomy,32,20,THPKWT/,THPKT,THPK,CCCC,CCCC,...,NaN,noH,3,f16_19,0,0,0,1,third,NaN
268298,2055670,4Q103a,Proverbs,10,31,THPKWT/,THPKWT,THPK,CCCC,CCCC,...,NaN,noH,2,f2,0,0,0,1,third,NaN
272830,2069684,4Q141,Deuteronomy,32,20,THPKWT/,THPWKWT,THPWK,CCCMC,CCCMC,...,NaN,noH,16,f1i,0,0,0,1,third,W

In [7]:
second = dat.query("type=='second'")

In [8]:
sec_lexemes = set(second.lex)

In [9]:
for lex in sec_lexemes:
    lex_df = second.query("lex==@lex")
    print(lex)
    print(set(lex_df.stem))
    print()

KRJTWT/
{'KRJTWT', 'KRTT', 'KRJTT'}

TLNWT/
{'TLNT', 'TLWNT'}

CRRWT/
{'CRJRWT', 'CRRWT'}

>R>LJ/
{'>RJ>L', '>R>L'}

NVWPTJ/
{'NVPT', 'NVWPT'}

>RMWN/
{'>RMWN', '>RWMN', '>RMN'}

YW>R/
{'YW>RT', 'YWR>'}

YMTT/
{'YMTT', 'YMJTT', 'YMJTWT'}

MSLWL/
{'MSWLL', 'MSLWL'}

XYYRH/
{'XYWYR', 'XYYR'}

JCJMWN/
{'JCJMWN', 'JCMWN', 'JCMN', 'JCJMN', 'JCWMWN'}

CLJCJT/
{'CLJCT', 'CLCJT', 'CLJCJT', 'CLCT'}

MDBR/
{'MDJBR', 'MDBR', 'MBDBR'}

R>CWN/
{'R>CN', 'RJ>CN', 'R>CWN', 'RJ>CWN', 'R>JCWN'}

M<ZN/
{'M<ZN', 'M<WZN'}

XMJCJT/
{'XMJCT', 'XMCJT', 'XMCT', 'XMJCJT'}

>J<ZRJ/
{'>XJ<ZR', '>J<ZR'}

HRJST/
{'HRST', 'HRWST'}

In [11]:
dat.query("g_cons=='R>JCWN'")

,tf_id,scroll,book,chapter,verse,lex,g_cons,stem,pattern,pattern_g_cons,...,other_vowel_ending,final_h,line,column,has_pronominal_suffix,has_prefix,has_hloc,has_nme,type,vowel_letter
158724,339800,MT,Job,15,7,R>CWN/,R>JCWN,R>JCWN,CMCCMC,CMCCMC,...,NaN,noH,-,-,0,1,0,0,second,NaN
158725,339800,MT,Job,15,7,R>CWN/,R>JCWN,R>JCWN,CMCCMC,CMCCMC,...,NaN,noH,-,-,0,1,0,0,first,>
158726,339800,MT,Job,15,7,R>CWN/,R>JCWN,R>JCWN,CMCCMC,CMCCMC,...,NaN,noH,-,-,0,1,0,0,last,W
200534,1890978,1Q3,Leviticus,23,7,R>CWN/,R>JCWN,R>JCWN,CMMCMC,CMMCMC,...,NaN,noH,4,f7,0,1,0,0,first,>J
200535,1890978,1Q3,Leviticus,23,7,R>CWN/,R>JCWN,R>JCWN,CMMCMC,CMMCMC,...,NaN,noH,4,f7,0,1,0,0,last,W
254186,2022647,4Q57,Isaiah,48,12,R>CWN/,R>JCWN,R>JCWN,CCMCMC,CCMCMC,...,NaN,noH,1,f29,0,0,0,0,last,W
254187,2022647,4Q57,Isaiah,48,12,R>CWN/,R>JCWN,R>JCWN,CCMCMC,CCMCMC,...,NaN,noH,1,f29,0,0,0,0,second,J
254188,2022647,4Q57,Isaiah,48,12,R>CWN/,R>JCWN,R>JCWN,CCMCMC,CCMCMC,...,NaN,noH,1,f29,0,0,0,0,first,NaN

In [ ]:
# CASES TO BE REMOVED WITH REASON:
YW>R/ {'YW>RT', 'YWR>'} mix of consonants
R>CWN/ {'R>CN', 'RJ>CN', 'R>CWN', 'RJ>CWN', 'R>JCWN'} On several places wrong parsing, e.g. MT tfid 339800, should be CMMCMC
>J<ZRJ/ {'>XJ<ZR', '>J<ZR'} strange extra X in word

In [12]:
# OTHER REMARKS
MDBR/ {'MDJBR', 'MDBR', 'MBDBR'} a bit strange, but maybe keep it.